### ISSUE TITLE
Unable to get sentence label value using SequenceTagger

### ISSUE THREAD

**Issue by howard0615** [zhangming880102/focus_driven_contrastive_learn-Software#1]
Hi, I've got a problem running the script of getting hard negative sample.

This is the issue what I face.

by running...

python focus_peturbation.py --sample_size 128 --batch 64 --dataset ../data/meqsum/json/train.jsonl --output ../data/meqsum/meqsum_contrast/constrast 

this was what I got

2022-11-13 12:54:39,331 SequenceTagger predicts: Dictionary with 45 tags: <unk>, O, B-NP, E-NP, I-NP, S-PP, S-VP, S-SBAR, S-ADVP, S-NP, S-ADJP, B-VP, E-VP, B-PP, E-PP, I-VP, S-PRT, B-ADVP, E-ADVP, B-ADJP, E-ADJP, B-CONJP, I-CONJP, E-CONJP, I-ADJP, B-SBAR, E-SBAR, S-INTJ, I-ADVP, I-PP, B-UCP, I-UCP, E-UCP, S-LST, B-PRT, I-PRT, E-PRT, S-CONJP, B-INTJ, E-INTJ, I-INTJ, B-LST, E-LST, <START>, <STOP>
construct vocabulary...
  0%|                                                                                                                                               | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "focus_peturbation.py", line 231, in <module>
    run(args)
  File "focus_peturbation.py", line 179, in run
    source_parse,source_toks=get_chunk_parse(args,s)
  File "focus_peturbation.py", line 81, in get_chunk_parse
    parse = [tok.labels[0].value for tok in sent.tokens]
  File "focus_peturbation.py", line 81, in <listcomp>
    parse = [tok.labels[0].value for tok in sent.tokens]
IndexError: list index out of range

**Comment by howard0615** [comment]
the version of Flair==0.11.3
